# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"classes": "mlflow_arduino.ipynb",
         "num_classes": "mlflow_arduino.ipynb",
         "input_list": "mlflow_arduino.ipynb",
         "output_list": "mlflow_arduino.ipynb",
         "e": "mlflow_arduino.ipynb",
         "X": "mlflow_arduino.ipynb",
         "y": "mlflow_arduino.ipynb",
         "model": "mlflow_arduino.ipynb",
         "history": "mlflow_arduino.ipynb",
         "converter": "mlflow_arduino.ipynb",
         "tflite_model": "mlflow_arduino.ipynb",
         "arduino_env": "mlflow_arduino.ipynb",
         "artifacts": "mlflow_arduino.ipynb",
         "ArduinoWrapper": "mlflow_arduino.ipynb",
         "PYTHON_VERSION": "mlflow_arduino.ipynb",
         "conda_env": "mlflow_arduino.ipynb"}

modules = ["train.py"]

doc_url = "https://nbdev.fast.ai/"

git_url = "https://github.com/fastai/nbdev/tree/master/"

def custom_doc_links(name): return None
